# Generated by Django 4.1.1 on 2022-09-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('auther_name', models.CharField(max_length=40)),
                ('release_year', models.CharField(max_length=5)),
                ('price', models.IntegerField()),
                ('membership', models.CharField(choices=[('Technology', 'Technology'), ('Religion', 'Religion'), ('Science & Research', 'Science & Research'), ('Politics & Laws', 'Politics & Laws'), ('Lifestyle', 'Lifestyle'), ('Fiction & Literature', 'Fiction & Literature')], default='Technology', max_length=100)),
            ],
        ),
    ]
